services:
  web:
    image: '${COMPOSE_PROJECT_NAME}-web'
    environment:
      - API_URL=${API_URL:-http://api:5000}
      - WEB_BASE_HREF=${WEB_BASE_HREF:-/probate/}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - BCEID_REGISTER_URL=${BCEID_REGISTER_URL}
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=notice
      - VITE_PORT=8080
      - CHOKIDAR_USEPOLLING=true
      - VITE_CHEFS_BASE_URL=${CHEFS_BASE_URL}
    ports:
      - '8080:8080'
    volumes:
      - '${LOCAL_WORKSPACE_FOLDER-..}/web/src:/opt/app-root/src/src'
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/package.json:/opt/app-root/src/packag\
        e.json"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/vite.config.js:/opt/app-root/src/vite\
        .config.js"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/tsconfig.json:/opt/app-root/src/tscon\
        fig.json"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/index.html:/opt/app-root/src/index.ht\
        ml"
    depends_on:
      - api

  api:
    image: '${COMPOSE_PROJECT_NAME}-api'
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - Database__ConnectionString=${DatabaseConnectionString}
      - Cors__AllowedOrigins=${CORS_DOMAIN}
      - Keycloak__Authority=${OIDC_RP_PROVIDER_ENDPOINT}
      - Keycloak__Client=${OIDC_RP_CLIENT_ID}
      - Keycloak__Secret=${OIDC_RP_CLIENT_SECRET}
      - Keycloak__KcIdpHint=${OIDC_RP_KC_IDP_HINT}
      - Keycloak__RefreshThreshold=${OIDC_RP_REFRESH_THRESHOLD:-00:05:00}
      - TokenRefreshThreshold=${TOKEN_REFRESH_THRESHOLD}
      - Chefs__Forms__legal__FormId=${CHEFS_FORM_LEGAL_FORMID}
      - Chefs__Forms__legal__ApiKey=${CHEFS_FORM_LEGAL_API_KEY}
      - Chefs__Forms__nonlegal__FormId=${CHEFS_FORM_NONLEGAL_FORMID}
      - Chefs__Forms__nonlegal__ApiKey=${CHEFS_FORM_NONLEGAL_API_KEY}
      - Chefs__BaseUrl=${CHEFS_BASE_URL}
      - CDogs__BaseUrl=${CDOGS_BASE_URL}
      - CDogs__TokenUrl=${CDOGS_TOKEN_URL}
      - CDogs__ClientId=${CDOGS_CLIENT_ID}
      - CDogs__ClientSecret=${CDOGS_CLIENT_SECRET}
      - EFiling__BaseUrl=${EFiling__BaseUrl}
      - EFiling__KeycloakBaseUrl=${EFiling__KeycloakBaseUrl}
      - EFiling__KeycloakRealm=${EFiling__KeycloakRealm}
      - EFiling__ClientId=${EFiling__ClientId}
      - EFiling__ClientSecret=${EFiling__ClientSecret}
    ports:
      - 5000:5000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-..}/api/:/opt/app-root/src/api
      - ${LOCAL_WORKSPACE_FOLDER-..}/db/:/opt/app-root/src/db
      - api-dev-bin:/opt/app-root/src/api/bin
      - api-dev-obj:/opt/app-root/src/api/obj
    depends_on:
      - db
    command: >
      /bin/bash -c "
        echo Waiting for the database service to start up ...;
        sleep 5;
        dotnet watch run --project /opt/app-root/src/api/api.csproj --urls='http://+:5000';"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  api-dev-bin:
  api-dev-obj:
  postgres-data:
