services:
  web:
    image: "${COMPOSE_PROJECT_NAME}-web"
    environment:
      - API_URL=${API_URL:-http://api:5000}
      - WEB_BASE_HREF=${WEB_BASE_HREF:-/probate/}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - BCEID_REGISTER_URL=${BCEID_REGISTER_URL}
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=notice
      - VITE_PORT=8080
      - CHOKIDAR_USEPOLLING=true
      - VITE_CHEFS_BASE_URL=${CHEFS_BASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/src:/opt/app-root/src/src"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/package.json:/opt/app-root/src/packag\
        e.json"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/vite.config.js:/opt/app-root/src/vite\
        .config.js"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/tsconfig.json:/opt/app-root/src/tscon\
        fig.json"
      - "${LOCAL_WORKSPACE_FOLDER-..}/web/index.html:/opt/app-root/src/index.ht\
        ml"
    depends_on:
      - api

  api:
    image: "${COMPOSE_PROJECT_NAME}-api"
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - Database__ConnectionString=${DatabaseConnectionString}
      - Cors__AllowedOrigins=${CORS_DOMAIN}
      - Keycloak__Authority=${OIDC_RP_PROVIDER_ENDPOINT}
      - Keycloak__Client=${OIDC_RP_CLIENT_ID}
      - Keycloak__Secret=${OIDC_RP_CLIENT_SECRET}
      - Keycloak__KcIdpHint=${OIDC_RP_KC_IDP_HINT}
      - Keycloak__RefreshThreshold=${OIDC_RP_REFRESH_THRESHOLD:-00:05:00}
      - TokenRefreshThreshold=${TOKEN_REFRESH_THRESHOLD}
      - Chefs__Forms__legal__FormId=${CHEFS_FORM_LEGAL_FORMID}
      - Chefs__Forms__legal__ApiKey=${CHEFS_FORM_LEGAL_API_KEY}
      - Chefs__Forms__nonlegal__FormId=${CHEFS_FORM_NONLEGAL_FORMID}
      - Chefs__Forms__nonlegal__ApiKey=${CHEFS_FORM_NONLEGAL_API_KEY}
      - Chefs__Forms__form-prequalifying-survey__FormId=${CHEFS_FORM_PREQUALIFYING_SURVEY_FORMID}
      - Chefs__Forms__form-prequalifying-survey__ApiKey=${CHEFS_FORM_PREQUALIFYING_SURVEY_API_KEY}
      - Chefs__Forms__form-prequalifying-survey__Order=${CHEFS_FORM_PREQUALIFYING_SURVEY_ORDER:-0}
      - Chefs__Forms__form-prequalifying-survey__Title=${CHEFS_FORM_PREQUALIFYING_SURVEY_TITLE:-Survey Questions}
      - Chefs__Forms__form-prequalifying-survey__Icon=${CHEFS_FORM_PREQUALIFYING_SURVEY_ICON:-list-check}
      - Chefs__Forms__form-deceased__FormId=${CHEFS_FORM_DECEASED_FORMID}
      - Chefs__Forms__form-deceased__ApiKey=${CHEFS_FORM_DECEASED_API_KEY}
      - Chefs__Forms__form-deceased__Order=${CHEFS_FORM_DECEASED_ORDER:-1}
      - Chefs__Forms__form-deceased__Title=${CHEFS_FORM_DECEASED_TITLE:-Deceased}
      - Chefs__Forms__form-deceased__Icon=${CHEFS_FORM_DECEASED_ICON:-skull}
      - Chefs__Forms__form-deceased__Children__0__Title=${CHEFS_FORM_DECEASED_CHILD_0_TITLE:-Information About Deceased}
      - Chefs__Forms__form-testamentary-docs__FormId=${CHEFS_FORM_TESTAMENTARY_DOCS_FORMID}
      - Chefs__Forms__form-testamentary-docs__ApiKey=${CHEFS_FORM_TESTAMENTARY_DOCS_API_KEY}
      - Chefs__Forms__form-testamentary-docs__Order=${CHEFS_FORM_TESTAMENTARY_DOCS_ORDER:-2}
      - Chefs__Forms__form-testamentary-docs__Title=${CHEFS_FORM_TESTAMENTARY_DOCS_TITLE:-Deceased's Will}
      - Chefs__Forms__form-testamentary-docs__Icon=${CHEFS_FORM_TESTAMENTARY_DOCS_ICON:-book}
      - Chefs__Forms__form-testamentary-docs__Children__0__Title=${CHEFS_FORM_TESTAMENTARY_DOCS_CHILD_0_TITLE:-Deceased's Will}
      - Chefs__Forms__form-related-people__FormId=${CHEFS_FORM_RELATED_PEOPLE_FORMID}
      - Chefs__Forms__form-related-people__ApiKey=${CHEFS_FORM_RELATED_PEOPLE_API_KEY}
      - Chefs__Forms__form-related-people__Order=${CHEFS_FORM_RELATED_PEOPLE_ORDER:-3}
      - Chefs__Forms__form-related-people__Title=${CHEFS_FORM_RELATED_PEOPLE_TITLE:-Related People}
      - Chefs__Forms__form-related-people__Icon=${CHEFS_FORM_RELATED_PEOPLE_ICON:-users}
      - Chefs__Forms__form-related-people__Children__0__Title=${CHEFS_FORM_RELATED_PEOPLE_CHILD_0_TITLE:-Spouse}
      - Chefs__Forms__form-related-people__Children__1__Title=${CHEFS_FORM_RELATED_PEOPLE_CHILD_1_TITLE:-Children}
      - Chefs__Forms__form-related-people__Children__2__Title=${CHEFS_FORM_RELATED_PEOPLE_CHILD_2_TITLE:-Creditors}
      - Chefs__Forms__form-applicant__FormId=${CHEFS_FORM_APPLICANT_FORMID}
      - Chefs__Forms__form-applicant__ApiKey=${CHEFS_FORM_APPLICANT_API_KEY}
      - Chefs__Forms__form-applicant__Order=${CHEFS_FORM_APPLICANT_ORDER:-4}
      - Chefs__Forms__form-applicant__Title=${CHEFS_FORM_APPLICANT_TITLE:-Applicant}
      - Chefs__Forms__form-applicant__Icon=${CHEFS_FORM_APPLICANT_ICON:-user-tie}
      - Chefs__Forms__form-applicant__Children__0__Title=${CHEFS_FORM_APPLICANT_CHILD_0_TITLE:-Information About Applicant}
      - Chefs__Forms__form-applicant__Children__1__Title=${CHEFS_FORM_APPLICANT_CHILD_1_TITLE:-Citor}
      - Chefs__Forms__form-applicant__Children__2__Title=${CHEFS_FORM_APPLICANT_CHILD_2_TITLE:-Applicant Service}
      - Chefs__Forms__form-notify__FormId=${CHEFS_FORM_NOTIFY_FORMID}
      - Chefs__Forms__form-notify__ApiKey=${CHEFS_FORM_NOTIFY_API_KEY}
      - Chefs__Forms__form-notify__Order=${CHEFS_FORM_NOTIFY_ORDER:-5}
      - Chefs__Forms__form-notify__Title=${CHEFS_FORM_NOTIFY_TITLE:-Notify}
      - Chefs__Forms__form-notify__Icon=${CHEFS_FORM_NOTIFY_ICON:-envelope-open-text}
      - Chefs__Forms__form-notify__Children__0__Title=${CHEFS_FORM_NOTIFY_CHILD_0_TITLE:-Review Your Answers}
      - Chefs__Forms__form-notify__Children__1__Title=${CHEFS_FORM_NOTIFY_CHILD_1_TITLE:-Tell People You Are Applying}
      - Chefs__Forms__form-notify__Children__2__Title=${CHEFS_FORM_NOTIFY_CHILD_2_TITLE:-Preview P1}
      - Chefs__Forms__form-notify__Children__3__Title=${CHEFS_FORM_NOTIFY_CHILD_3_TITLE:-Preview PGT}
      - Chefs__Forms__form-notify__Children__4__Title=${CHEFS_FORM_NOTIFY_CHILD_4_TITLE:-Notify People}
      - Chefs__Forms__form-assets__FormId=${CHEFS_FORM_ASSETS_FORMID}
      - Chefs__Forms__form-assets__ApiKey=${CHEFS_FORM_ASSETS_API_KEY}
      - Chefs__Forms__form-assets__Order=${CHEFS_FORM_ASSETS_ORDER:-6}
      - Chefs__Forms__form-assets__Title=${CHEFS_FORM_ASSETS_TITLE:-Assets}
      - Chefs__Forms__form-assets__Icon=${CHEFS_FORM_ASSETS_ICON:-coins}
      - Chefs__Forms__form-assets__Children__0__Title=${CHEFS_FORM_ASSETS_CHILD_0_TITLE:-Assets Details}
      - Chefs__Forms__form-application-documents__FormId=${CHEFS_FORM_APPLICATION_DOCUMENTS_FORMID}
      - Chefs__Forms__form-application-documents__ApiKey=${CHEFS_FORM_APPLICATION_DOCUMENTS_API_KEY}
      - Chefs__Forms__form-application-documents__Order=${CHEFS_FORM_APPLICATION_DOCUMENTS_ORDER:-7}
      - Chefs__Forms__form-application-documents__Title=${CHEFS_FORM_APPLICATION_DOCUMENTS_TITLE:-Application Documents}
      - Chefs__Forms__form-application-documents__Icon=${CHEFS_FORM_APPLICATION_DOCUMENTS_ICON:-file-lines}
      - Chefs__Forms__form-application-documents__Children__0__Title=${CHEFS_FORM_APPLICATION_DOCUMENTS_CHILD_0_TITLE:-Preview P9}
      - Chefs__Forms__form-application-documents__Children__1__Title=${CHEFS_FORM_APPLICATION_DOCUMENTS_CHILD_1_TITLE:-Fill out a Form P5}
      - Chefs__Forms__form-application-documents__Children__2__Title=${CHEFS_FORM_APPLICATION_DOCUMENTS_CHILD_2_TITLE:-Fill out a Form P10}
      - Chefs__Forms__form-application-documents__Children__3__Title=${CHEFS_FORM_APPLICATION_DOCUMENTS_CHILD_3_TITLE:-Fill out an Application for Search of Wills Notice}
      - Chefs__Forms__form-application-documents__Children__4__Title=${CHEFS_FORM_APPLICATION_DOCUMENTS_CHILD_4_TITLE:-Fill out a Form P2}
      - Chefs__Forms__form-filing__FormId=${CHEFS_FORM_FILING_FORMID}
      - Chefs__Forms__form-filing__ApiKey=${CHEFS_FORM_FILING_API_KEY}
      - Chefs__Forms__form-filing__Order=${CHEFS_FORM_FILING_ORDER:-8}
      - Chefs__Forms__form-filing__Title=${CHEFS_FORM_FILING_TITLE:-Filing Instructions}
      - Chefs__Forms__form-filing__Icon=${CHEFS_FORM_FILING_ICON:-file-arrow-up}
      - Chefs__Forms__form-filing__Children__0__Title=${CHEFS_FORM_FILING_CHILD_0_TITLE:-Filing Instructions}
      - Chefs__BaseUrl=${CHEFS_BASE_URL}
      - CDogs__BaseUrl=${CDOGS_BASE_URL}
      - CDogs__TokenUrl=${CDOGS_TOKEN_URL}
      - CDogs__ClientId=${CDOGS_CLIENT_ID}
      - CDogs__ClientSecret=${CDOGS_CLIENT_SECRET}
      - EFiling__BaseUrl=${EFiling__BaseUrl}
      - EFiling__KeycloakBaseUrl=${EFiling__KeycloakBaseUrl}
      - EFiling__KeycloakRealm=${EFiling__KeycloakRealm}
      - EFiling__ClientId=${EFiling__ClientId}
      - EFiling__ClientSecret=${EFiling__ClientSecret}
    ports:
      - 5000:5000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-..}/api/:/opt/app-root/src/api
      - ${LOCAL_WORKSPACE_FOLDER-..}/db/:/opt/app-root/src/db
      - api-dev-bin:/opt/app-root/src/api/bin
      - api-dev-obj:/opt/app-root/src/api/obj
    depends_on:
      - db
    command: >
      /bin/bash -c "
        echo Waiting for the database service to start up ...;
        sleep 5;
        dotnet watch run --project /opt/app-root/src/api/api.csproj --urls='http://+:5000';"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  api-dev-bin:
  api-dev-obj:
  postgres-data:
