name: Validate GitHub Actions

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
  merge_group:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate workflows
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2
        with:
          version: 1.7.12
          files: |
            .github/workflows/*.yml
